[manager]
manager    ansible_host=93.77.185.60 ansible_user=sasha
[nodes]
node1 ansible_host=89.169.153.58 ansible_user=sasha
node2 ansible_host=93.77.181.50 ansible_user=sasha
#node3 ansible_host=192.168.1.96 ansible_user=sasha
