name: Quick DAG Check1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
#on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'dags/**'
jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install tools
        run: |
          pip install flake8 bandit pylint # black
      
#      - name: Check formatting
#        run: black --check dags/

      - name: Lint
        run: flake8 dags/ --max-line-length=120 --count --statistics

      - name: Static analysis with pylint
        run: |
          pylint dags/ \
            --fail-under=8.0 \
            --disable=import-error,no-name-in-module \
            --exit-zero \
            --output-format=colorized
        continue-on-error: true

      # 5. Анализ безопасности с bandit
      - name: Security analysis with bandit
        run: |
          bandit -r dags/ \
            --format=sarif \
            #--output=bandit-results.sarif \
            --severity-level high \
            --confidence-level high

      - run: echo "🍏 This job's status is ${{ job.status }}."
