name:  SAST dag check
run-name: ${{ github.actor }} is running out GitHub Actions workflow 🚀
on: [push]
#on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'dags/**'
jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of branch is ${{ github.ref }} and repository is ."
      - uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install tools (flake8, bandit, pylint, secret-scan)
        run: |
          pip install flake8 bandit pylint secret-scan

      - name: Lint (flake8)
        run: flake8 dags/ --max-line-length=120 --count --statistics

      - name: Static analysis with pylint
        run: |
          pylint dags/ \
            --fail-under=8.0 \
            --disable=import-error,no-name-in-module \
            --exit-zero \
            --output-format=colorized
        continue-on-error: true

      # 5. Анализ безопасности с bandit
      - name: Security analysis with bandit
        run: |
          bandit -r dags/ \
            --format=json \

      - name: Scan for secrets
        run: secret-scan dags/     # scanner exits with code 1 if secrets are found, which will fail the workflow

      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "Static analisys on vulnerability completed"
